apiVersion: v1
kind: Service
metadata:
  name: predictive-analytics-api
  namespace: predictive-analytics
spec:
  selector:
    app: predictive-analytics-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
