apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-analytics-flink-job
  namespace: predictive-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictive-analytics-flink-job
  template:
    metadata:
      labels:
        app: predictive-analytics-flink-job
    spec:
      containers:
        - name: flink-job
          image: predictive-analytics-flink-job:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: predictive-analytics-config
            - secretRef:
                name: predictive-analytics-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
