apiVersion: v1
kind: Secret
metadata:
  name: predictive-analytics-secrets
  namespace: predictive-analytics
type: Opaque
data:
  POSTGRES_PASSWORD: YW5hbHl0aWNz
  SPRING_DATASOURCE_PASSWORD: YW5hbHl0aWNz
