{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "reliability-pack.fullname" . }}
  labels:
    {{- include "reliability-pack.labels" . | nindent 4 }}
spec:
  groups:
{{- toYaml .Values.prometheusRule.groups | nindent 4 }}
{{- end }}
