apiVersion: 1

datasources:
  - name: Predictions Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: analytics
    user: analytics
    secureJsonData:
      password: analytics
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
