cloudProvider: azure

autoDiscovery:
  clusterName: finops-aks

azureUseManagedIdentityExtension: true
azureResourceGroup: <RESOURCE_GROUP>
azureSubscriptionID: <SUBSCRIPTION_ID>
azureTenantID: <TENANT_ID>
azureVMType: vmss

extraArgs:
  expander: least-waste
  balance-similar-node-groups: "true"
  skip-nodes-with-system-pods: "false"
  skip-nodes-with-local-storage: "false"
