{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secure-rag.fullname" . }}
  labels:
    {{- include "secure-rag.labels" . | nindent 4 }}
{{- end -}}
