global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jenkins"
    static_configs:
      - targets: ["jenkins:8080"]
  - job_name: "portal"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["portal:8080"]
