cloudProvider: gce

autoscalingGroupsnamePrefix:
  - name: gke-finops-default-pool
    minSize: 1
    maxSize: 6

extraArgs:
  expander: least-waste
  balance-similar-node-groups: "true"
  skip-nodes-with-system-pods: "false"
  skip-nodes-with-local-storage: "false"
