apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  namespace: cicd-demo
spec:
  type: ClusterIP
  selector:
    app: cicd-demo
    track: stable
  ports:
    - port: 80
      targetPort: 8080
