apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-portal.fullname" . }}
  labels:
    {{ include "platform-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "platform-portal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{ include "platform-portal.labels" . | nindent 8 }}
    spec:
      containers:
        - name: portal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{ toYaml .Values.env | nindent 12 }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20