apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-portal.fullname" . }}
  labels:
    {{ include "platform-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "platform-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}